name: python-deployment

run-name: ${{ github.actor }} - ${{ github.ref_name }} - ${{ github.sha }}

env:
  PythonVersion: 3.8

on: 
  push: 
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]

jobs:
  python-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PythonVersion }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PythonVersion }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8 . --show-source --statistics
      - name: Check Complexity
        run: |
          cd ../
          flake8 . --exit-zero --max-complexity=10 --statistics
      - name: Test with pytest
        run: |	
          pytest -v --cov-report=term-missing --cov=. --cov-report=json







